title: "Mamadou Kane"
description: "Data Analyst | BI | Statistiques | Power BI | SQL | R"
theme: jekyll-theme-cayman

# (optionnel) pour afficher un bouton vers ton LinkedIn
show_downloads: false

# (optionnel) si tu as un repo du type mamadou-kane.github.io
# baseurl: ""
# url: "https://mamadou-kane.github.io"

